import { CreditCard, Plus, Sparkles } from "lucide-react";
import { createPaymentMethodAction, createServiceAction, togglePaymentMethodAction, updateServiceAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { getCatalogData } from "@/lib/cached-data";
import { formatMoney } from "@/lib/money";
import { requireAdmin } from "@/lib/session";

export const metadata = { title: "Services" };
export default async function ServicesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const { services, methods, settings } = await getCatalogData();
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Catalogue</span><h1>Services & payments</h1><p>Manage POS choices without changing historical receipts.</p></div></div><Flash success={query.success} error={query.error} /><div className="grid two-grid"><div className="card"><div className="card-head"><h2>Services</h2><span className="badge">{services.length} total</span></div><div className="table-wrap"><table><thead><tr><th>Service</th><th>Price</th><th>Status</th><th>Update</th></tr></thead><tbody>{services.map((service) => <tr key={service.id}><td><strong>{service.name}</strong><small className="muted" style={{ display: "block" }}>{service.description || "No description"}</small></td><td className="amount">{formatMoney(service.price, settings?.currencyCode)}</td><td><span className={`badge ${service.isActive ? "success" : ""}`}>{service.isActive ? "Active" : "Inactive"}</span></td><td><form action={updateServiceAction} className="inline-form"><input type="hidden" name="id" value={service.id} /><input className="input" name="price" defaultValue={service.price} required /><select className="input" name="isActive" defaultValue={String(service.isActive)}><option value="true">Active</option><option value="false">Inactive</option></select><button className="btn btn-soft">Save</button></form></td></tr>)}</tbody></table></div></div>
      <div className="grid"><form action={createServiceAction} className="card card-pad"><div className="card-head" style={{ padding: 0, marginBottom: 18 }}><h2><Sparkles size={17} style={{ display: "inline", marginRight: 7 }} /> Add service</h2></div><div className="field"><label>Name</label><input className="input" name="name" required /></div><div className="field" style={{ marginTop: 12 }}><label>Price</label><input className="input" name="price" inputMode="decimal" placeholder="0.00" required /></div><div className="field" style={{ marginTop: 12 }}><label>Description</label><textarea className="input" name="description" /></div><button className="btn btn-primary btn-block" style={{ marginTop: 15 }}><Plus size={16} /> Add service</button></form>
      <div className="card card-pad"><div className="card-head" style={{ padding: 0, marginBottom: 14 }}><h2><CreditCard size={17} style={{ display: "inline", marginRight: 7 }} /> Payment methods</h2></div>{methods.map((method) => <div className="checkout-row" key={method.id}><span>{method.name}</span><form action={togglePaymentMethodAction}><input type="hidden" name="id" value={method.id} /><input type="hidden" name="isActive" value={String(!method.isActive)} /><button className={`btn ${method.isActive ? "btn-ghost" : "btn-soft"}`}>{method.isActive ? "Deactivate" : "Activate"}</button></form></div>)}<form action={createPaymentMethodAction} className="inline-form" style={{ marginTop: 15 }}><input className="input" name="name" placeholder="New payment method" required /><button className="btn btn-primary"><Plus size={15} /></button></form></div></div>
    </div></div>;
}
