import Link from "next/link";
import { Download, FileBarChart, Search } from "lucide-react";
import { Prisma } from "@prisma/client";
import { Empty } from "@/components/empty";
import { formatDateTime, parseDateRange } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/session";
import { stockSnapshot } from "@/modules/inventory/stock";

export const metadata = { title: "Reports" };
const reportNames = ["Daily sales", "Monthly sales", "Sales by service", "Sales by supervisor", "Sales by payment method", "Receipt history", "Cancelled receipts", "General expenses", "Worker commissions", "Supervisor salaries", "Purchases", "Current stock", "Low-stock items", "Inventory issued", "Damaged & lost", "Movement history", "Cash summary"];
export default async function ReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const { start, end } = parseDateRange(query.from, query.to);
  const [receipts, expenses, purchaseItems, movements, issues, stock, settings] = await Promise.all([
    prisma.receipt.findMany({ where: { issuedAt: { gte: start, lte: end } }, include: { createdByUser: true, paymentMethod: true }, orderBy: { issuedAt: "desc" }, take: 100 }),
    prisma.expense.findMany({ where: { expenseDate: { gte: start, lte: end } }, include: { supervisor: true, category: true }, orderBy: { expenseDate: "desc" }, take: 100 }),
    prisma.purchaseItem.findMany({ where: { purchase: { status: "RECEIVED", purchaseDate: { gte: start, lte: end } } }, include: { purchase: { include: { supplier: true } }, inventoryItem: true } }),
    prisma.inventoryMovement.findMany({ where: { createdAt: { gte: start, lte: end } }, include: { inventoryItem: true, createdByUser: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.inventoryIssue.findMany({ where: { issueDate: { gte: start, lte: end } }, include: { supervisor: true, items: { include: { inventoryItem: true } } }, orderBy: { issueDate: "desc" }, take: 100 }), stockSnapshot(), prisma.businessSetting.findUnique({ where: { id: "singleton" } }),
  ]);
  const completed = receipts.filter((row) => row.status === "COMPLETED"), activeExpenses = expenses.filter((row) => row.status === "ACTIVE" && row.paymentStatus === "PAID");
  const sales = completed.reduce((sum, row) => sum.add(row.servicePriceSnapshot), new Prisma.Decimal(0)); const expenseTotal = activeExpenses.reduce((sum, row) => sum.add(row.amount), new Prisma.Decimal(0)); const purchases = purchaseItems.reduce((sum, row) => sum.add(row.quantity.mul(row.unitCost)), new Prisma.Decimal(0)); const cash = sales.sub(expenseTotal).sub(purchases); const currency = settings?.currencyCode ?? "USD";
  const byService = group(completed, (row) => row.serviceNameSnapshot, (row) => row.servicePriceSnapshot); const bySupervisor = group(completed, (row) => row.createdByUser.fullName, (row) => row.servicePriceSnapshot); const byPayment = group(completed, (row) => row.paymentMethod.name, (row) => row.servicePriceSnapshot);
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Decision support</span><h1>Reports</h1><p>Every figure is recalculated from transaction records for the selected period.</p></div><Link className="btn btn-primary" href={`/api/reports/csv?type=sales&from=${query.from ?? ""}&to=${query.to ?? ""}`}><Download size={16} /> Export sales CSV</Link></div>
    <form className="card filters"><div className="field"><label>From</label><input className="input" type="date" name="from" defaultValue={query.from} /></div><div className="field"><label>To</label><input className="input" type="date" name="to" defaultValue={query.to} /></div><button className="btn btn-primary"><Search size={15} /> Apply period</button><div className="actions"><Link className="btn btn-ghost" href={`/api/reports/csv?type=expenses&from=${query.from ?? ""}&to=${query.to ?? ""}`}>Expenses CSV</Link><Link className="btn btn-ghost" href={`/api/reports/csv?type=purchases&from=${query.from ?? ""}&to=${query.to ?? ""}`}>Purchases CSV</Link><Link className="btn btn-ghost" href="/api/reports/csv?type=stock">Stock CSV</Link></div></form>
    <div className="grid stats-grid section-gap"><Summary label="Completed sales" value={formatMoney(sales, currency)} note={`${completed.length} receipts`} /><Summary label="Paid expenses" value={formatMoney(expenseTotal, currency)} note={`${activeExpenses.length} active records`} /><Summary label="Received purchases" value={formatMoney(purchases, currency)} note={`${purchaseItems.length} line items`} /><Summary label="Cash summary" value={formatMoney(cash, currency)} note="Sales − paid expenses − purchases" /></div>
    <div className="card card-pad section-gap"><h2>Available report views</h2><div className="actions" style={{ marginTop: 15 }}>{reportNames.map((name) => <span className="badge" key={name}><FileBarChart size={11} /> {name}</span>)}</div><p className="muted" style={{ fontSize: 12, marginBottom: 0 }}>Cash summary is operational cash movement, not a full profit-and-loss statement.</p></div>
    <div className="grid three-grid section-gap"><Group title="Sales by service" rows={byService} currency={currency} /><Group title="Sales by supervisor" rows={bySupervisor} currency={currency} /><Group title="Sales by payment method" rows={byPayment} currency={currency} /></div>
    <div className="grid two-grid section-gap"><div className="card"><div className="card-head"><h2>Receipt and cancellation history</h2></div>{!receipts.length ? <Empty /> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Receipt</th><th>Service</th><th>Supervisor</th><th>Total</th><th>Status</th></tr></thead><tbody>{receipts.map((row) => <tr key={row.id}><td>{formatDateTime(row.issuedAt)}</td><td>#{String(row.id).padStart(6, "0")}</td><td>{row.serviceNameSnapshot}</td><td>{row.createdByUser.fullName}</td><td>{formatMoney(row.servicePriceSnapshot, currency)}</td><td><span className={`badge ${row.status === "COMPLETED" ? "success" : "danger"}`}>{row.status}</span></td></tr>)}</tbody></table></div>}</div><div className="card"><div className="card-head"><h2>Expenses by type</h2></div>{!expenses.length ? <Empty /> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Title</th><th>Amount</th><th>Status</th></tr></thead><tbody>{expenses.map((row) => <tr key={row.id}><td>{formatDateTime(row.expenseDate)}</td><td>{row.type.replaceAll("_", " ")}</td><td>{row.title}</td><td>{formatMoney(row.amount, currency)}</td><td>{row.status}</td></tr>)}</tbody></table></div>}</div></div>
    <div className="grid two-grid section-gap"><div className="card"><div className="card-head"><h2>Current and low stock</h2></div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Owned</th><th>Assigned</th><th>Available</th><th>Level</th></tr></thead><tbody>{stock.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.owned.toString()}</td><td>{row.assigned.toString()}</td><td>{row.available.toString()}</td><td><span className={`badge ${row.available.lessThanOrEqualTo(row.minimumStockLevel) ? "warning" : "success"}`}>{row.available.lessThanOrEqualTo(row.minimumStockLevel) ? "Low" : "OK"}</span></td></tr>)}</tbody></table></div></div><div className="card"><div className="card-head"><h2>Issued, damaged, lost & movements</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Movement</th><th>Qty</th></tr></thead><tbody>{movements.map((row) => <tr key={row.id}><td>{formatDateTime(row.createdAt)}</td><td>{row.inventoryItem.name}</td><td>{row.movementType.replaceAll("_", " ")}</td><td>{row.quantity.toString()}</td></tr>)}</tbody></table></div><p className="muted" style={{ padding: "0 20px" }}>{issues.length} inventory issues in period.</p></div></div>
  </div>;
}
function group<T>(rows: T[], key: (row: T) => string, value: (row: T) => Prisma.Decimal) { const result = new Map<string, { count: number; total: Prisma.Decimal }>(); for (const row of rows) { const name = key(row), current = result.get(name) ?? { count: 0, total: new Prisma.Decimal(0) }; current.count += 1; current.total = current.total.add(value(row)); result.set(name, current); } return [...result].map(([name, data]) => ({ name, ...data })); }
function Summary({ label, value, note }: { label: string; value: string; note: string }) { return <div className="card stat"><div className="stat-top">{label}</div><div className="stat-value">{value}</div><div className="stat-note">{note}</div></div>; }
function Group({ title, rows, currency }: { title: string; rows: { name: string; count: number; total: Prisma.Decimal }[]; currency: string }) { return <div className="card card-pad"><h2>{title}</h2>{rows.length ? rows.map((row) => <div className="checkout-row" key={row.name}><span>{row.name}<small className="muted" style={{ display: "block" }}>{row.count} receipts</small></span><strong>{formatMoney(row.total, currency)}</strong></div>) : <p className="muted">No completed sales.</p>}</div>; }
