import Link from "next/link";
import { Boxes, Plus, SlidersHorizontal, Truck } from "lucide-react";
import { adjustStockAction, createInventoryCategoryAction, createInventoryItemAction, createSupplierAction } from "@/app/actions";
import { Empty } from "@/components/empty";
import { Flash } from "@/components/flash";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/session";
import { stockSnapshot } from "@/modules/inventory/stock";

export const metadata = { title: "Inventory" };
export default async function InventoryPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const [stock, categories, suppliers] = await Promise.all([stockSnapshot(), prisma.inventoryCategory.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }), prisma.supplier.findMany({ where: { isActive: true }, orderBy: { name: "asc" } })]);
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Stock control</span><h1>Inventory</h1><p>Quantities are calculated from immutable stock movements.</p></div><div className="actions"><Link className="btn btn-soft" href="/inventory/issues"><Truck size={16} /> Issues & returns</Link><Link className="btn btn-primary" href="/purchases"><Plus size={16} /> Register purchase</Link></div></div><Flash success={query.success} error={query.error} />
    <div className="card"><div className="card-head"><h2>Current stock</h2><span className="badge">{stock.length} active items</span></div>{!stock.length ? <Empty message="Add an inventory item to begin tracking stock." /> : <div className="table-wrap"><table><thead><tr><th>Item</th><th>Type</th><th>Category</th><th>Owned</th><th>Assigned</th><th>Available</th><th>Minimum</th></tr></thead><tbody>{stock.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="muted" style={{ display: "block" }}>{item.sku} · {item.unit}</small></td><td><span className="badge">{item.type}</span></td><td>{item.category.name}</td><td className="amount">{item.owned.toString()}</td><td className="amount">{item.assigned.toString()}</td><td className={`amount ${item.available.lessThanOrEqualTo(item.minimumStockLevel) ? "text-danger" : ""}`}>{item.available.toString()}</td><td>{item.minimumStockLevel.toString()}</td></tr>)}</tbody></table></div>}</div>
    <div className="grid three-grid section-gap"><form action={createInventoryItemAction} className="card card-pad"><span className="stat-icon"><Boxes size={18} /></span><h2 style={{ marginTop: 15 }}>Add inventory item</h2><div className="field"><label>Name</label><input className="input" name="name" required /></div><div className="form-grid" style={{ marginTop: 12 }}><div className="field"><label>SKU</label><input className="input" name="sku" required /></div><div className="field"><label>Type</label><select className="input" name="type"><option>CONSUMABLE</option><option>REUSABLE</option></select></div><div className="field"><label>Category</label><select className="input" name="categoryId" required>{categories.map((row) => <option value={row.id} key={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Unit</label><select className="input" name="unit"><option>Litre</option><option>Bottle</option><option>Piece</option><option>Kilogram</option><option>Box</option></select></div><div className="field full"><label>Minimum stock</label><input className="input" name="minimumStockLevel" defaultValue="0" required /></div></div><button className="btn btn-primary btn-block" style={{ marginTop: 15 }}><Plus size={15} /> Add item</button></form>
      <div className="grid"><form action={createInventoryCategoryAction} className="card card-pad"><h2>Categories</h2><p className="muted">{categories.map((row) => row.name).join(" · ") || "No categories"}</p><div className="inline-form"><input className="input" name="name" placeholder="New category" required /><button className="btn btn-primary"><Plus size={15} /></button></div></form><form action={createSupplierAction} className="card card-pad"><h2>Suppliers</h2><p className="muted">{suppliers.length} active supplier{suppliers.length === 1 ? "" : "s"}</p><div className="field"><label>Name</label><input className="input" name="name" required /></div><div className="field" style={{ marginTop: 9 }}><label>Phone</label><input className="input" name="phone" /></div><button className="btn btn-primary btn-block" style={{ marginTop: 12 }}><Plus size={15} /> Add supplier</button></form></div>
      <form action={adjustStockAction} className="card card-pad"><span className="stat-icon"><SlidersHorizontal size={18} /></span><h2 style={{ marginTop: 15 }}>Manual adjustment</h2><p className="muted">Corrections create a new movement and require a reason.</p><div className="field"><label>Item</label><select className="input" name="inventoryItemId" required>{stock.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="form-grid" style={{ marginTop: 12 }}><div className="field"><label>Direction</label><select className="input" name="direction"><option value="IN">Add stock</option><option value="OUT">Remove stock</option></select></div><div className="field"><label>Quantity</label><input className="input" name="quantity" required /></div></div><div className="field" style={{ marginTop: 12 }}><label>Reason</label><textarea className="input" name="reason" minLength={5} required /></div><button className="btn btn-primary btn-block" style={{ marginTop: 15 }}>Post adjustment</button></form></div>
  </div>;
}
