"use client";

import { Plus, Trash2 } from "lucide-react";
import { useMemo, useRef, useState } from "react";

export type PurchaseItemOption = { id: string; name: string; sku?: string; unit?: string };
export type PurchaseLineValue = { inventoryItemId: string; quantity: string; unitCost: string };

export function PurchaseLinesEditor({ items, initial }: { items: PurchaseItemOption[]; initial?: PurchaseLineValue[] }) {
  const sequence = useRef((initial?.length ?? 1) + 1);
  const [lines, setLines] = useState(() => (initial?.length ? initial : [{ inventoryItemId: items[0]?.id ?? "", quantity: "", unitCost: "" }]).map((line, index) => ({ ...line, key: `purchase-line-${index + 1}` })));
  const selected = useMemo(() => new Set(lines.map((line) => line.inventoryItemId)), [lines]);
  function update(key: string, patch: Partial<PurchaseLineValue>) { setLines((current) => current.map((line) => line.key === key ? { ...line, ...patch } : line)); }
  function add() { const inventoryItemId = items.find((item) => !selected.has(item.id))?.id ?? ""; setLines((current) => [...current, { key: `purchase-line-${sequence.current++}`, inventoryItemId, quantity: "", unitCost: "" }]); }
  const serialized = lines.map((line) => ({ inventoryItemId: line.inventoryItemId, quantity: line.quantity, unitCost: line.unitCost }));
  return <div className="line-editor"><input type="hidden" name="itemsJson" value={JSON.stringify(serialized)} /><div className="line-editor-head"><div><strong>Purchase items</strong><span>{lines.length} {lines.length === 1 ? "line" : "lines"}</span></div><button className="btn btn-soft btn-compact" type="button" disabled={lines.length >= items.length} onClick={add}><Plus size={14} /> Add item</button></div>{lines.map((line, index) => { const item = items.find((row) => row.id === line.inventoryItemId); const total = Number(line.quantity || 0) * Number(line.unitCost || 0); return <div className="purchase-line-row" key={line.key}><span className="line-number">{index + 1}</span><div className="field purchase-item-field"><label htmlFor={`${line.key}-item`}>Inventory item</label><select className="input" id={`${line.key}-item`} value={line.inventoryItemId} onChange={(event) => update(line.key, { inventoryItemId: event.target.value })} required>{items.map((row) => <option key={row.id} value={row.id} disabled={row.id !== line.inventoryItemId && selected.has(row.id)}>{row.name}{row.sku ? ` · ${row.sku}` : ""}</option>)}</select></div><div className="field"><label htmlFor={`${line.key}-quantity`}>Quantity {item?.unit ? `(${item.unit})` : ""}</label><input className="input" id={`${line.key}-quantity`} value={line.quantity} onChange={(event) => update(line.key, { quantity: event.target.value })} inputMode="decimal" pattern="\d+(\.\d{1,3})?" placeholder="0.000" required /></div><div className="field"><label htmlFor={`${line.key}-cost`}>Unit cost</label><input className="input" id={`${line.key}-cost`} value={line.unitCost} onChange={(event) => update(line.key, { unitCost: event.target.value })} inputMode="decimal" pattern="\d+(\.\d{1,2})?" placeholder="0.00" required /></div><div className="line-total"><span>Line total</span><strong>{Number.isFinite(total) ? total.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : "0.00"}</strong></div><button className="icon-button line-remove" type="button" aria-label={`Remove purchase line ${index + 1}`} disabled={lines.length === 1} onClick={() => setLines((current) => current.filter((row) => row.key !== line.key))}><Trash2 size={16} /></button></div>; })}</div>;
}
