import { Plus, UserRoundCheck } from "lucide-react";
import { createSupervisorAction, toggleSupervisorAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { formatDateTime } from "@/lib/dates";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/session";

export const metadata = { title: "Supervisors" };
export default async function SupervisorsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const users = await prisma.user.findMany({ where: { role: "SUPERVISOR" }, orderBy: { createdAt: "desc" }, include: { _count: { select: { receiptsCreated: true } } } });
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Access control</span><h1>Supervisors</h1><p>Staff can sign in from any browser POS device.</p></div></div><Flash success={query.success} error={query.error} /><div className="grid two-grid"><div className="card"><div className="card-head"><h2>Supervisor accounts</h2><span className="badge">{users.length}</span></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Username</th><th>Receipts</th><th>Created</th><th>Account status</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.fullName}</strong></td><td>@{user.displayUsername || user.username}</td><td>{user._count.receiptsCreated}</td><td>{formatDateTime(user.createdAt)}</td><td><div className="actions"><span className={`badge ${user.isActive ? "success" : "danger"}`}>{user.isActive ? "Active" : "Disabled"}</span><form action={toggleSupervisorAction}><input type="hidden" name="id" value={user.id} /><input type="hidden" name="isActive" value={String(!user.isActive)} /><button className={`btn ${user.isActive ? "btn-danger" : "btn-soft"}`}>{user.isActive ? "Disable account" : "Enable account"}</button></form></div></td></tr>)}</tbody></table></div></div>
    <form action={createSupervisorAction} className="card card-pad"><span className="stat-icon" style={{ marginBottom: 16 }}><UserRoundCheck size={19} /></span><h2>Create supervisor</h2><p className="muted">Passwords are hashed by Better Auth and never stored in plain text.</p><div className="field"><label>Full name</label><input className="input" name="fullName" required /></div><div className="field" style={{ marginTop: 12 }}><label>Username</label><input className="input" name="username" minLength={3} autoComplete="off" required /></div><div className="field" style={{ marginTop: 12 }}><label>Temporary password</label><input className="input" type="password" name="password" minLength={10} autoComplete="new-password" required /></div><button className="btn btn-primary btn-block" style={{ marginTop: 16 }}><Plus size={16} /> Create account</button></form></div></div>;
}
