import { PackagePlus, Plus } from "lucide-react";
import { Prisma } from "@prisma/client";
import { createPurchaseAction, receivePurchaseAction } from "@/app/actions";
import { Empty } from "@/components/empty";
import { Flash } from "@/components/flash";
import { getCatalogData, getPurchaseLedger, getReferenceData } from "@/lib/cached-data";
import { formatDateTime } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { requireAdmin } from "@/lib/session";

export const metadata = { title: "Purchases" };
export default async function PurchasesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const [purchases, catalog, references] = await Promise.all([
    getPurchaseLedger(),
    getCatalogData(), getReferenceData(),
  ]);
  const suppliers = references.suppliers, methods = catalog.methods.filter((row) => row.isActive), items = references.inventoryItems, settings = catalog.settings;
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Stock intake</span><h1>Purchases</h1><p>Drafts do not change stock. Receiving posts every movement atomically.</p></div></div><Flash success={query.success} error={query.error} /><div className="grid two-grid"><div className="card"><div className="card-head"><h2>Purchase history</h2></div>{!purchases.length ? <Empty message="No purchases registered." /> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Supplier</th><th>Invoice</th><th>Items</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{purchases.map((purchase) => { const total = new Prisma.Decimal(purchase.total); return <tr key={purchase.id}><td>{formatDateTime(purchase.purchaseDate)}</td><td>{purchase.supplier.name}</td><td>{purchase.supplierInvoiceNumber || "—"}</td><td>{purchase.items.map((row) => `${row.inventoryItem.name} × ${row.quantity}`).join(", ")}</td><td className="amount">{formatMoney(total, settings?.currencyCode)}</td><td><span className={`badge ${purchase.status === "RECEIVED" ? "success" : purchase.status === "CANCELLED" ? "danger" : "warning"}`}>{purchase.status}</span></td><td>{purchase.status === "DRAFT" && <form action={receivePurchaseAction}><input type="hidden" name="id" value={purchase.id} /><button className="btn btn-soft">Receive</button></form>}</td></tr>; })}</tbody></table></div>}</div>
      <form action={createPurchaseAction} className="card card-pad"><span className="stat-icon"><PackagePlus size={18} /></span><h2 style={{ marginTop: 15 }}>Register purchase</h2><p className="muted">This creates a draft. Review it in the list, then receive it.</p><div className="form-grid"><div className="field"><label>Supplier</label><select className="input" name="supplierId" required>{suppliers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Purchase date</label><input className="input" type="date" name="purchaseDate" defaultValue={new Date().toISOString().slice(0, 10)} required /></div><div className="field"><label>Payment method</label><select className="input" name="paymentMethodId"><option value="">Select</option>{methods.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Payment status</label><select className="input" name="paymentStatus"><option>PAID</option><option>UNPAID</option></select></div><div className="field full"><label>Supplier invoice</label><input className="input" name="supplierInvoiceNumber" /></div><div className="field full"><label>Inventory item</label><select className="input" name="inventoryItemId" required>{items.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Quantity</label><input className="input" name="quantity" required /></div><div className="field"><label>Unit cost</label><input className="input" name="unitCost" required /></div><div className="field full"><label>Notes</label><textarea className="input" name="notes" /></div></div><button className="btn btn-primary btn-block" style={{ marginTop: 16 }}><Plus size={16} /> Create draft</button></form></div></div>;
}
