import { CircleDollarSign, Plus } from "lucide-react";
import { cancelExpenseAction, createExpenseAction } from "@/app/actions";
import { Empty } from "@/components/empty";
import { Flash } from "@/components/flash";
import { formatDateTime } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/session";

export const metadata = { title: "Expenses" };
const today = () => new Date().toISOString().slice(0, 10);
export default async function ExpensesPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin(); const query = await searchParams; const page = Math.max(Number(query.page) || 1, 1); const take = 25;
  const [expenses, total, categories, supervisors, methods, settings] = await Promise.all([
    prisma.expense.findMany({ include: { category: true, supervisor: true, paymentMethod: true }, orderBy: [{ expenseDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * take, take }),
    prisma.expense.count(), prisma.expenseCategory.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }),
    prisma.user.findMany({ where: { role: "SUPERVISOR", isActive: true }, orderBy: { fullName: "asc" } }),
    prisma.paymentMethod.findMany({ where: { isActive: true }, orderBy: { name: "asc" } }), prisma.businessSetting.findUnique({ where: { id: "singleton" } }),
  ]);
  return <div className="page"><div className="page-head"><div><span className="eyebrow">Money out</span><h1>Expenses</h1><p>General costs, worker commissions, and supervisor salaries in one auditable ledger.</p></div></div><Flash success={query.success} error={query.error} />
    <div className="grid two-grid"><div className="card"><div className="card-head"><h2>Expense history</h2><span className="badge">{total}</span></div>{!expenses.length ? <Empty message="No expenses recorded yet." /> : <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Title</th><th>For</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id}><td>{formatDateTime(expense.expenseDate)}</td><td><span className="badge">{expense.type.replaceAll("_", " ")}</span></td><td><strong>{expense.title}</strong>{expense.carCount && <small className="muted" style={{ display: "block" }}>{expense.carCount} cars × {formatMoney(expense.ratePerCar ?? 0, settings?.currencyCode)}</small>}</td><td>{expense.supervisor?.fullName ?? expense.category?.name ?? "—"}</td><td className="amount">{formatMoney(expense.amount, settings?.currencyCode)}</td><td>{expense.paymentStatus}</td><td><span className={`badge ${expense.status === "ACTIVE" ? "success" : "danger"}`}>{expense.status}</span></td><td>{expense.status === "ACTIVE" && <form action={cancelExpenseAction} className="inline-form"><input type="hidden" name="id" value={expense.id} /><input className="input" name="reason" placeholder="Reason" minLength={5} required /><button className="btn btn-danger">Cancel</button></form>}</td></tr>)}</tbody></table></div>}</div>
      <form action={createExpenseAction} className="card card-pad"><span className="stat-icon" style={{ marginBottom: 16 }}><CircleDollarSign size={19} /></span><h2>Record expense</h2><p className="muted">For commission, the server calculates cars × rate and checks receipt count.</p><div className="form-grid"><div className="field full"><label>Expense type</label><select className="input" name="type" required><option value="GENERAL">General expense</option><option value="WORKER_COMMISSION">Worker commission</option><option value="SUPERVISOR_SALARY">Supervisor salary</option></select></div><div className="field full"><label>Title</label><input className="input" name="title" required /></div><div className="field"><label>Date</label><input className="input" type="date" name="expenseDate" defaultValue={today()} required /></div><div className="field"><label>Payment status</label><select className="input" name="paymentStatus"><option>PAID</option><option>UNPAID</option></select></div><div className="field"><label>Category (general)</label><select className="input" name="categoryId"><option value="">Select</option>{categories.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Supervisor (commission/salary)</label><select className="input" name="supervisorUserId"><option value="">Select</option>{supervisors.map((row) => <option key={row.id} value={row.id}>{row.fullName}</option>)}</select></div><div className="field"><label>Amount (general/salary)</label><input className="input" name="amount" inputMode="decimal" placeholder="0.00" /></div><div className="field"><label>Payment method</label><select className="input" name="paymentMethodId"><option value="">Select</option>{methods.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></div><div className="field"><label>Cars (commission)</label><input className="input" name="carCount" type="number" min="1" /></div><div className="field"><label>Rate per car</label><input className="input" name="ratePerCar" inputMode="decimal" /></div><div className="field"><label>Period start (salary)</label><input className="input" type="date" name="periodStart" /></div><div className="field"><label>Period end (salary)</label><input className="input" type="date" name="periodEnd" /></div><div className="field full"><label>Override reason (if commission cars exceed receipts)</label><input className="input" name="overrideReason" /></div><div className="field full"><label>Notes</label><textarea className="input" name="notes" /></div></div><button className="btn btn-primary btn-block" style={{ marginTop: 16 }}><Plus size={16} /> Record expense</button></form>
    </div></div>;
}
